### ISSUE TITLE
FE: ARTISTE PAGE

### ISSUE THREAD

**Issue by thedanielwilliams** [elcharitas/muxifi#58]
Trello Card: [https://trello.com/c/fRgLMsJE](https://trello.com/c/fRgLMsJE)

**Comment by oke-yomi** [comment]
Working on this tomorrow. I'm working on the collections ATM

The Playlist page has been updated as well

**Comment by thedanielwilliams** [comment]
> 

Hi Yomi, this issue is still open, though. Are you facing any challenges?

**Comment by elcharitas** [comment]
Closed by #71
